# Generated by Django 2.2.15 on 2020-12-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0022_courseoverviewtab_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='difficulty_level',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='difficulty_level',
            field=models.TextField(null=True),
        ),
    ]
