# Generated by Django 2.2.15 on 2020-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0023_auto_20201201_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Difficulty Level',
            },
        ),
    ]
