# Generated by Django 2.2.15 on 2020-12-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0025_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='subcategory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='subcategory',
            field=models.TextField(null=True),
        ),
    ]
