# Generated by Django 2.2.15 on 2020-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_auto_20201203_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_category'),
        ),
    ]
