# Generated by Django 2.2.15 on 2020-12-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0027_auto_20201211_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseoverview',
            old_name='category',
            new_name='new_category',
        ),
        migrations.RenameField(
            model_name='historicalcourseoverview',
            old_name='category',
            new_name='new_category',
        ),
    ]
