# Generated by Django 2.2.15 on 2020-12-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0028_auto_20201216_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='course_sale_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='platform_visibility',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='course_sale_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='platform_visibility',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
