# Generated by Django 2.2.15 on 2021-01-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0030_auto_20201224_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='indexed_in_discovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='indexed_in_discovery',
            field=models.BooleanField(default=False),
        ),
    ]
