# Generated by Django 2.2.15 on 2021-01-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0031_auto_20210106_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoverview',
            name='indexed_in_discovery',
        ),
        migrations.RemoveField(
            model_name='historicalcourseoverview',
            name='indexed_in_discovery',
        ),
    ]
