# Generated by Django 2.2.15 on 2021-03-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0033_auto_20210108_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoverview',
            name='new_category',
        ),
        migrations.RemoveField(
            model_name='courseoverview',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='historicalcourseoverview',
            name='new_category',
        ),
        migrations.RemoveField(
            model_name='historicalcourseoverview',
            name='subcategory',
        ),
    ]
