# Generated by Django 2.2.15 on 2021-03-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0034_auto_20210330_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='new_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_overviews.Category'),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_overviews.SubCategory'),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='new_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_overviews.Category'),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='subcategory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_overviews.SubCategory'),
        ),
    ]
