# Generated by Django 2.2.15 on 2021-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0035_auto_20210330_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='platform_visibility',
            field=models.TextField(default='Both'),
        ),
        migrations.AlterField(
            model_name='historicalcourseoverview',
            name='platform_visibility',
            field=models.TextField(default='Both'),
        ),
    ]
