# Generated by Django 2.2.18 on 2021-03-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0035_auto_20210330_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='allow_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='allow_review',
            field=models.BooleanField(default=True),
        ),
    ]
