# Generated by Django 2.2.18 on 2021-04-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0037_auto_20210402_1126'),
        ('course_overviews', '0036_auto_20210331_1531'),
    ]

    operations = [
    ]
