# Generated by Django 2.2.19 on 2021-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0038_merge_20210405_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='published_in_ecommerce',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='published_in_ecommerce',
            field=models.BooleanField(null=True),
        ),
    ]
