# Generated by Django 2.2.15 on 2021-01-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0006_auto_20210105_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='currency',
            field=models.CharField(default='usd', help_text='Lower-case ISO currency codes', max_length=8),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='currency',
            field=models.CharField(default='usd', help_text='Lower-case ISO currency codes', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='usd', max_length=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(default='usd', max_length=8),
        ),
    ]
