# Generated by Django 2.2.18 on 2021-03-29 10:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faq_images/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'FaqCategory',
                'verbose_name_plural': 'FaqCategory',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('question', models.CharField(max_length=1200)),
                ('answer', ckeditor.fields.RichTextField(blank=True)),
                ('view_count', models.IntegerField(default=0, editable=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.FaqCategory')),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faq',
            },
        ),
    ]
