# Generated by Django 2.2.18 on 2021-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_img',
            field=models.ImageField(upload_to='../media/banner/lms/courses'),
        ),
    ]
