# Generated by Django 2.2.19 on 2021-04-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20210420_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='course_over_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_over_view', to='course_overviews.CourseOverview'),
        ),
    ]
