# Generated by Django 2.2.15 on 2021-01-12 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20191022_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountpercentageconfig',
            name='percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
