# Generated by Django 2.2.18 on 2021-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhub_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='days_warning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('not_active', 'Not active'), ('first_not_completed', 'First not completed'), ('second_not_completed', 'Second not completed')], max_length=64),
        ),
    ]
