# Generated by Django 2.2.15 on 2021-01-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0014_auto_20210105_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='currency',
            field=models.CharField(default='sgd', max_length=8),
        ),
        migrations.AlterField(
            model_name='coursemodesarchive',
            name='currency',
            field=models.CharField(default='sgd', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='currency',
            field=models.CharField(default='sgd', max_length=8),
        ),
    ]
