# Generated by Django 2.2.15 on 2021-03-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0016_auto_20210105_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='min_price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='min_price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
    ]
