# Generated by Django 2.2.15 on 2021-03-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0017_auto_20210317_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemode',
            name='discount_percentage',
            field=models.FloatField(default=0.0, verbose_name='Discount Percentage'),
        ),
        migrations.AddField(
            model_name='historicalcoursemode',
            name='discount_percentage',
            field=models.FloatField(default=0.0, verbose_name='Discount Percentage'),
        ),
    ]
