# Generated by Django 2.2.18 on 2021-03-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0017_auto_20210315_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='currency',
            field=models.CharField(default='usd', max_length=8),
        ),
        migrations.AlterField(
            model_name='coursemodesarchive',
            name='currency',
            field=models.CharField(default='usd', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='currency',
            field=models.CharField(default='usd', max_length=8),
        ),
    ]
