# Generated by Django 2.2.18 on 2021-03-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0017_auto_20210317_1114'),
        ('course_modes', '0019_auto_20210315_1128'),
    ]

    operations = [
    ]
