# Generated by Django 2.2.18 on 2021-03-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0020_merge_20210317_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Price'),
        ),
    ]
