# Generated by Django 2.2.18 on 2021-03-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0020_merge_20210317_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemode',
            name='discount_percentage',
            field=models.FloatField(default=0.0, verbose_name='Discount Percentage'),
        ),
        migrations.AddField(
            model_name='historicalcoursemode',
            name='discount_percentage',
            field=models.FloatField(default=0.0, verbose_name='Discount Percentage'),
        ),
    ]
