# Generated by Django 2.2.18 on 2021-03-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_modes', '0021_auto_20210324_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemode',
            name='min_price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicalcoursemode',
            name='min_price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
    ]
