# Generated by Django 2.2.15 on 2020-12-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='review',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
