# Generated by Django 2.2.15 on 2020-12-11 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20201203_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
