# Generated by Django 2.2.15 on 2020-12-28 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0002_userextrainfo_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_org', to='organizations.Organization'),
        ),
    ]
