# Generated by Django 2.2.15 on 2020-12-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0003_auto_20201228_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_industry', to='course_overviews.Category'),
        ),
    ]
