# Generated by Django 2.2.15 on 2021-01-01 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0005_auto_20210101_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrainfo',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 1, 1), verbose_name='Date of birth'),
            preserve_default=False,
        ),
    ]
