# Generated by Django 2.2.15 on 2021-01-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0006_userextrainfo_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextrainfo',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
