# Generated by Django 2.2.15 on 2021-01-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0007_auto_20210101_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
