# Generated by Django 2.2.15 on 2021-01-19 10:49

import custom_reg_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0010_auto_20210112_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='date_of_birth',
            field=models.DateField(blank=True, default='2000-01-01', null=True, validators=[custom_reg_form.models.age_validator], verbose_name='Date of birth'),
        ),
    ]
