# Generated by Django 2.2.15 on 2021-01-19 11:04

import custom_reg_form.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0012_auto_20210119_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1), validators=[custom_reg_form.models.age_validator], verbose_name='Date of birth'),
        ),
    ]
