# Generated by Django 2.2.15 on 2021-01-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0013_auto_20210119_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='industry',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_industry', to='course_overviews.Category'),
        ),
    ]
