# Generated by Django 2.2.20 on 2021-05-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_type', models.CharField(max_length=250)),
                ('incentive_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition_type', models.CharField(max_length=250)),
                ('condition_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_datetime', models.DateTimeField(verbose_name='date published')),
                ('end_datetime', models.DateTimeField(verbose_name='date published')),
                ('priority', models.CharField(max_length=250)),
                ('is_exclusive', models.BooleanField()),
                ('associated_ecommerce_offer_id', models.IntegerField()),
            ],
        ),
    ]
