# Generated by Django 2.2.20 on 2021-05-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0039_auto_20210406_1433'),
        ('lhub_ecommerce_offer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='offer',
            name='course',
            field=models.ManyToManyField(to='course_overviews.CourseOverview'),
        ),
    ]
