# Generated by Django 2.2.20 on 2021-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhub_ecommerce_offer', '0002_auto_20210510_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
