# Generated by Django 2.2.20 on 2021-05-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lhub_ecommerce_offer', '0004_offer_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='is_active',
            new_name='is_suspended',
        ),
    ]
