# Generated by Django 2.2.20 on 2021-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0039_auto_20210406_1433'),
        ('lhub_ecommerce_offer', '0005_auto_20210517_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=250)),
                ('incentive_type', models.CharField(max_length=250)),
                ('incentive_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usage', models.CharField(max_length=250)),
                ('start_datetime', models.DateTimeField(verbose_name='start date')),
                ('end_datetime', models.DateTimeField(verbose_name='end date')),
                ('is_exclusive', models.BooleanField()),
                ('associated_ecommerce_coupon_id', models.IntegerField()),
                ('course', models.ManyToManyField(to='course_overviews.CourseOverview')),
            ],
        ),
    ]
