# Generated by Django 2.2.20 on 2021-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhub_ecommerce_offer', '0006_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_datetime',
            field=models.DateTimeField(null=True, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='start datetime'),
        ),
    ]
