# Generated by Django 2.2.15 on 2021-01-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_userprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_birth',
            field=models.IntegerField(db_index=True, default=2020),
            preserve_default=False,
        ),
    ]
