# Generated by Django 2.2.15 on 2021-01-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_auto_20210101_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_birth',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
