# Generated by Django 2.2.18 on 2021-03-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_auto_20201021_1256'),
        ('student', '0038_auto_20210119_0759'),
    ]

    operations = [
    ]
